# Generated by Django 5.1.4 on 2025-02-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
