# Generated by Django 5.1.4 on 2024-12-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_country_options_alter_nationality_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='highschool',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialization',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
