# Generated by Django 5.1.4 on 2025-02-22 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_is_expelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpulsionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('verdict_date', models.DateTimeField(blank=True, null=True)),
                ('verdict', models.CharField(choices=[('C', 'Confirmed'), ('R', 'Rejected')], max_length=1, null=True)),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.expulsionreason')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
