# Generated by Django 5.1.4 on 2025-02-24 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_expulsionrequest_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expulsionrequest',
            options={'ordering': ['verdict_date']},
        ),
        migrations.AddField(
            model_name='expulsionrequest',
            name='viewed_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
