# Generated by Django 5.1.4 on 2025-02-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_expulsionrequest_viewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expulsionrequest',
            name='is_obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
