# Generated by Django 5.1.4 on 2024-12-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='degree',
        ),
    ]
