# Generated by Django 5.1.4 on 2024-12-25 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_specialization_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='degree',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='api.degree'),
            preserve_default=False,
        ),
    ]
