# Generated by Django 5.1.4 on 2025-02-24 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_reinstaterequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expulsionrequest',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expulsion_request_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reinstaterequest',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinstate_request_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
