# Generated by Django 5.1.4 on 2025-01-05 08:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_specialization_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Oglan'), ('F', 'Gyz')], max_length=1)),
                ('family_status', models.CharField(choices=[('FR', 'Hossarly'), ('HO', 'Ýarym ýetim'), ('CO', 'Doly ýetim'), ('OE', 'Ýetimler öýünde ösen')], max_length=2)),
                ('payment_type', models.CharField(choices=[], max_length=2)),
                ('birth_date', models.DateField(default=datetime.date(1970, 1, 1))),
                ('admission_type', models.DateField()),
                ('registered_place', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('passport', models.CharField(max_length=20)),
                ('military_service', models.CharField(blank=True, max_length=20, null=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.country')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.nationality')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.region')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.specialization')),
            ],
        ),
    ]
