# Generated by Django 5.1.4 on 2025-02-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_expulsionrequest_sender_reinstaterequest_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expulsionrequest',
            name='verdict',
            field=models.CharField(blank=True, choices=[('C', 'Confirmed'), ('R', 'Rejected')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='reinstaterequest',
            name='verdict',
            field=models.CharField(blank=True, choices=[('C', 'Confirmed'), ('R', 'Rejected')], max_length=1, null=True),
        ),
    ]
