# Generated by Django 5.1.4 on 2025-01-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_student_name_remove_student_patronymic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_type',
            field=models.CharField(choices=[('P', 'Tölegli'), ('B', 'Býudjet')], max_length=1),
        ),
    ]
