# Generated by Django 5.1.4 on 2025-02-26 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_expulsionrequest_verdict_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma_count', models.PositiveIntegerField(default=0)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('verdict_date', models.DateTimeField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('C', 'Confirmed'), ('R', 'Rejected')], max_length=1, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('previous_update_date', models.DateTimeField(auto_now_add=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diploma_request_sender', to=settings.AUTH_USER_MODEL)),
                ('viewed_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiplomaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_year_work_off', models.PositiveIntegerField(default=0)),
                ('died', models.PositiveIntegerField(default=0)),
                ('went_abroad', models.PositiveIntegerField(default=0)),
                ('other_reasons', models.PositiveIntegerField(default=0)),
                ('verdict_date', models.DateTimeField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('C', 'Confirmed')], max_length=1, null=True)),
                ('diploma_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.diplomarequest')),
            ],
        ),
        migrations.CreateModel(
            name='DiplomaRequestAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_to', models.PositiveIntegerField(default=0)),
                ('verdict_date', models.DateTimeField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('C', 'Confirmed')], max_length=1, null=True)),
                ('diploma_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.diplomarequest')),
            ],
        ),
    ]
