# Generated by Django 5.1.4 on 2025-01-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_student_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admission_type',
            new_name='admission_date',
        ),
    ]
