# Generated by Django 5.1.4 on 2025-02-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_diplomarequest_previous_update_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomarequest',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
