# Generated by Django 5.1.4 on 2025-02-26 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_diplomarequest_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomareport',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diplomarequestaction',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
