# Generated by Django 5.1.4 on 2025-01-16 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_specialization_degree_alter_student_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='high_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.highschool'),
        ),
    ]
