# Generated by Django 5.1.4 on 2025-02-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_diplomareport_request_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diplomarequest',
            old_name='diploma_count',
            new_name='honor_diploma_count',
        ),
        migrations.RemoveField(
            model_name='diplomarequestaction',
            name='update_to',
        ),
        migrations.AddField(
            model_name='diplomarequest',
            name='simple_diploma_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diplomarequestaction',
            name='update_honor_to',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diplomarequestaction',
            name='update_simple_to',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
