# Generated by Django 5.1.4 on 2025-01-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_student_high_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='study_year',
            field=models.IntegerField(default=1),
        ),
    ]
