# Generated by Django 5.1.4 on 2025-02-27 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_diploma_count_diplomarequest_honor_diploma_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diplomarequest',
            name='update_date',
        ),
        migrations.AddField(
            model_name='diplomarequest',
            name='allowed_until',
            field=models.DateField(default=datetime.datetime(2025, 3, 29, 18, 9, 7, 176203, tzinfo=datetime.timezone.utc)),
        ),
    ]
