# Generated by Django 5.1.4 on 2025-02-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_student_active_student_study_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profile'),
        ),
    ]
