# Generated by Django 5.1.4 on 2025-02-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_highschool_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='lat',
            field=models.FloatField(blank=True, default=37.95),
        ),
        migrations.AddField(
            model_name='highschool',
            name='lng',
            field=models.FloatField(blank=True, default=58.38),
        ),
    ]
