# Generated by Django 5.1.4 on 2025-02-27 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_diplomarequest_allowed_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomarequest',
            name='allowed_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 18, 48, 19, 369137, tzinfo=datetime.timezone.utc)),
        ),
    ]
