# Generated by Django 5.1.4 on 2025-02-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_highschool_lat_highschool_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highschool',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='highschool',
            name='faculties',
        ),
        migrations.RemoveField(
            model_name='highschool',
            name='specializations',
        ),
        migrations.CreateModel(
            name='HighSchoolFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.faculty')),
                ('high_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.highschool')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('high_school_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.highschoolfaculty')),
            ],
        ),
    ]
