# Generated by Django 5.1.4 on 2025-02-28 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_diplomarequest_allowed_until'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diplomareport',
            options={'ordering': ['-verdict_date']},
        ),
        migrations.AlterModelOptions(
            name='diplomarequestaction',
            options={'ordering': ['-verdict_date']},
        ),
        migrations.AlterField(
            model_name='diplomarequest',
            name='allowed_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 30, 4, 16, 52, 583937, tzinfo=datetime.timezone.utc)),
        ),
    ]
