# Generated by Django 5.1.4 on 2025-02-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_highschool_departments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.facultydepartment')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specialization')),
            ],
        ),
    ]
