# Generated by Django 5.1.4 on 2025-03-01 17:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_diplomareport_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomarequest',
            name='allowed_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 17, 28, 52, 296540, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='TeacherStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload_1_25', models.PositiveIntegerField(default=0)),
                ('workload_1_00', models.PositiveIntegerField(default=0)),
                ('workload_0_75', models.PositiveIntegerField(default=0)),
                ('workload_0_50', models.PositiveIntegerField(default=0)),
                ('doctor_degree', models.PositiveIntegerField(default=0)),
                ('candidate_degree', models.PositiveIntegerField(default=0)),
                ('allowed_until', models.DateTimeField(default=datetime.datetime(2025, 3, 31, 17, 28, 52, 298206, tzinfo=datetime.timezone.utc))),
                ('is_obsolete', models.BooleanField(default=False)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('verdict_date', models.DateTimeField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('C', 'Confirmed'), ('R', 'Rejected')], max_length=1, null=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_statement_sender', to=settings.AUTH_USER_MODEL)),
                ('viewed_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
