# Generated by Django 5.1.4 on 2025-02-04 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_departmentspecialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='degree',
        ),
        migrations.AddField(
            model_name='departmentspecialization',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.degree'),
        ),
    ]
