# Generated by Django 5.1.4 on 2025-02-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_specialization_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentspecialization',
            name='specialization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.specialization'),
        ),
        migrations.AlterField(
            model_name='facultydepartment',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
        migrations.AlterField(
            model_name='highschoolfaculty',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.faculty'),
        ),
    ]
