# Generated by Django 5.1.4 on 2025-03-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_teacherstatement_deparment_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomarequest',
            name='allowed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherstatement',
            name='allowed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
