# Generated by Django 5.1.4 on 2025-02-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_departmentspecialization_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentspecialization',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specialization'),
        ),
        migrations.AlterField(
            model_name='facultydepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
        migrations.AlterField(
            model_name='highschoolfaculty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.departmentspecialization'),
        ),
    ]
