# Generated by Django 5.1.4 on 2025-03-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_diplomarequest_allowed_until_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherstatement',
            old_name='deparment_head',
            new_name='department_head',
        ),
    ]
