# Generated by Django 5.1.4 on 2025-03-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_deparment_head_teacherstatement_department_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
