# Generated by Django 5.1.4 on 2025-03-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_highschool_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='study_year',
            field=models.CharField(max_length=3),
        ),
    ]
