# Generated by Django 5.1.4 on 2025-03-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_student_study_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_year',
            field=models.CharField(default='1', max_length=3),
        ),
    ]
