# Generated by Django 5.1.4 on 2025-03-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_student_is_obsolete_alter_student_study_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualUpdateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
