# Generated by Django 5.1.4 on 2025-03-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_annualupdatereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualupdatereport',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
