# Generated by Django 5.1.4 on 2025-04-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_student_military_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_service',
            field=models.CharField(choices=[('bmdu', 'BMDU'), ('mmu', 'MMU'), ('both', 'Both Services'), ('none', 'None of them')], default='none', max_length=20),
        ),
    ]
