# Generated by Django 5.1.4 on 2025-04-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_profile_allowed_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
