# Generated by Django 5.1.4 on 2025-04-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_profile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
