# Generated by Django 5.1.4 on 2025-04-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
