# Generated by Django 5.2.1 on 2025-07-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmdu_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentspecialization',
            name='is_common_shell',
        ),
        migrations.AddField(
            model_name='departmentspecialization',
            name='identification_status',
            field=models.CharField(choices=[('P', 'Bölek'), ('CS', 'Umumylaşdyrlan'), ('D', 'Ýönekeý')], default='D', max_length=2),
        ),
    ]
