# Generated by Django 5.1.4 on 2025-05-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmdu_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='military_service',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=500),
        ),
    ]
