# Generated by Django 5.2.1 on 2025-06-20 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmdu_api', '0002_alter_student_military_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultydepartment',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='facultydepartment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bmdu_api.department'),
        ),
    ]
