# Generated by Django 5.2.1 on 2025-07-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmdu_api', '0002_remove_departmentspecialization_is_common_shell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentspecialization',
            name='shell_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
