# Generated by Django 5.2.1 on 2025-06-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmdu_api', '0003_facultydepartment_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
