# Generated by Django 5.2.1 on 2025-07-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmdu_api', '0004_department_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentspecialization',
            name='is_common_shell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departmentspecialization',
            name='parts',
            field=models.ManyToManyField(blank=True, to='bmdu_api.departmentspecialization'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='is_complex_branched',
            field=models.BooleanField(default=False),
        ),
    ]
