# Generated by Django 5.2.1 on 2025-07-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmdu_api', '0005_departmentspecialization_is_common_shell_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentspecialization',
            name='faculty_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bmdu_api.facultydepartment'),
        ),
        migrations.AlterField(
            model_name='departmentspecialization',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bmdu_api.specialization'),
        ),
    ]
