# Generated by Django 5.2.1 on 2025-07-03 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('allowed_service', models.CharField(choices=[('bmdu', 'BMDU'), ('mmu', 'MMU'), ('both', 'Both Services'), ('none', 'None of them')], default='none', max_length=20)),
                ('otp', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('role', models.CharField(default='default', max_length=100)),
                ('temp_key', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
