# Generated by Django 5.1.4 on 2025-04-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedIP',
        ),
    ]
