# Generated by Django 5.1.4 on 2025-05-19 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('mmu_api', '0002_course_educationcentercourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationcenter',
            old_name='personal',
            new_name='workers',
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='books_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='building_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='rooms_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.profile'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content', models.FileField(upload_to='mmu/')),
                ('is_active', models.BooleanField(default=True)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.profile')),
            ],
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='files',
            field=models.ManyToManyField(to='mmu_api.file'),
        ),
    ]
