# Generated by Django 5.1.4 on 2025-05-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmu_api', '0003_rename_personal_educationcenter_workers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenter',
            name='files',
            field=models.ManyToManyField(blank=True, to='mmu_api.file'),
        ),
    ]
