# Generated by Django 5.1.4 on 2025-04-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_profile_temp_key'),
        ('mmu_api', '0003_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenter',
            name='personal',
            field=models.ManyToManyField(blank=True, to='api.profile'),
        ),
    ]
