# Generated by Django 5.2.1 on 2025-05-20 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmu_api', '0004_alter_educationcenter_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationcenter',
            old_name='building_count',
            new_name='buildings_count',
        ),
    ]
