# Generated by Django 5.2.1 on 2025-05-21 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmu_api', '0005_rename_building_count_educationcenter_buildings_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenter',
            name='accreditation_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accredition_file', to='mmu_api.file'),
        ),
    ]
