# Generated by Django 5.2.1 on 2025-05-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmu_api', '0006_educationcenter_accreditation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenter',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
