# Generated by Django 5.2.1 on 2025-05-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmu_api', '0007_educationcenter_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenter',
            name='books_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='educationcenter',
            name='buildings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='educationcenter',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='educationcenter',
            name='rooms_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
