# Generated by Django 5.2.1 on 2025-05-21 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('mmu_api', '0008_alter_educationcenter_books_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_to', to='main.profile'),
        ),
        migrations.AddField(
            model_name='file',
            name='to_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mmu_api.educationcenter'),
        ),
    ]
