# Generated by Django 5.2.1 on 2025-05-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmu_api', '0009_file_to_file_to_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='courses',
            field=models.ManyToManyField(to='mmu_api.course'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('place_of_residence', models.TextField()),
                ('phone_number', models.CharField(max_length=100)),
                ('education_degree', models.CharField(choices=[('high', 'High'), ('incompleteHigh', 'Incomplete High'), ('secondary', 'Secondary'), ('specialSecondary', 'Special Secondary')], max_length=20)),
                ('specializations', models.ManyToManyField(to='mmu_api.specialization')),
            ],
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='staff',
            field=models.ManyToManyField(to='mmu_api.staff'),
        ),
    ]
