# Generated by Django 5.2.1 on 2025-05-27 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('mmu_api', '0010_specialization_educationcenter_courses_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationcenter',
            name='files',
        ),
        migrations.AddField(
            model_name='staff',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.country'),
        ),
        migrations.AddField(
            model_name='staff',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region'),
        ),
    ]
