# Generated by Django 5.2.1 on 2025-05-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmu_api', '0012_staff_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenter',
            name='courses',
            field=models.ManyToManyField(blank=True, to='mmu_api.course'),
        ),
        migrations.AlterField(
            model_name='educationcenter',
            name='staff',
            field=models.ManyToManyField(blank=True, to='mmu_api.staff'),
        ),
    ]
