# Generated by Django 5.2.1 on 2025-05-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmu_api', '0013_alter_educationcenter_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='specializations',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
