# Generated by Django 5.2.1 on 2025-05-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmu_api', '0015_specialization_specializationtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='specializations',
            field=models.ManyToManyField(to='mmu_api.specialization'),
        ),
    ]
